/*
 *  Copyright (C) 2010 nickapos
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * AboutWindow.java
 * This class will create a window with a text area and depending on the need
 * will present in the text are a message, be it an about or a readme.
 * Created on 11 Αυγ 2010, 9:51:33 μμ
 */
package gr.oncrete.nick.mybill.UserInterface;

import gr.oncrete.nick.myBill.BusinessLogic.Amortization;
import gr.oncrete.nick.myBill.BusinessLogic.AmortizationTable;

/**
 *
 * @author nickapos
 */
public class CalculateAmortizationFrame extends javax.swing.JFrame {

    /** Creates new form AboutWindow */
    public CalculateAmortizationFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        amountTextField = new javax.swing.JTextField();
        periodLabel = new javax.swing.JLabel();
        periodTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        payoffFrequencyComboBox = new javax.swing.JComboBox();
        rateLabel = new javax.swing.JLabel();
        rateTextField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        calcAmortizationTableButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        presentResultLabel = new javax.swing.JLabel();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("gr/oncrete/nick/myBill/UserInterface/myBillUIBundle"); // NOI18N
        jTextField1.setText(bundle.getString("CalculateAmortizationFrame.jTextField1.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(bundle.getString("CalculateAmortizationFrame.title")); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout(6, 2));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(bundle.getString("CalculateAmortizationFrame.jLabel2.text")); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2);
        getContentPane().add(amountTextField);

        periodLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        periodLabel.setText(bundle.getString("CalculateAmortizationFrame.periodLabel.text")); // NOI18N
        getContentPane().add(periodLabel);

        periodTextField.setText(bundle.getString("CalculateAmortizationFrame.periodTextField.text")); // NOI18N
        periodTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(periodTextField);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(bundle.getString("CalculateAmortizationFrame.jLabel3.text")); // NOI18N
        getContentPane().add(jLabel3);

        payoffFrequencyComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "One month", "Three months", "Six months", "One year" }));
        getContentPane().add(payoffFrequencyComboBox);

        rateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rateLabel.setText(bundle.getString("CalculateAmortizationFrame.rateLabel.text")); // NOI18N
        rateLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(rateLabel);

        rateTextField.setText(bundle.getString("CalculateAmortizationFrame.rateTextField.text")); // NOI18N
        getContentPane().add(rateTextField);

        calculateButton.setText(bundle.getString("CalculateAmortizationFrame.calculateButton.text")); // NOI18N
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(calculateButton);

        calcAmortizationTableButton.setText(bundle.getString("CalculateAmortizationFrame.calcAmortizationTableButton.text")); // NOI18N
        calcAmortizationTableButton.setEnabled(false);
        calcAmortizationTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcAmortizationTableButtonActionPerformed(evt);
            }
        });
        getContentPane().add(calcAmortizationTableButton);

        resultLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        resultLabel.setText(bundle.getString("CalculateAmortizationFrame.resultLabel.text")); // NOI18N
        getContentPane().add(resultLabel);

        presentResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        presentResultLabel.setText(bundle.getString("CalculateAmortizationFrame.presentResultLabel.text")); // NOI18N
        getContentPane().add(presentResultLabel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        String amountStr = amountTextField.getText().replaceAll(",", ".");
        String periodStr = periodTextField.getText();
        String rateStr = rateTextField.getText().replaceAll(",", ".");

        if (amountStr.length() > 0 && periodStr.length() > 0 && rateStr.length() > 0) {

            Amortization am = this.calculateAmortization();
            presentResultLabel.setText(am.calculateAmortization());
            calcAmortizationTableButton.setEnabled(true);
        }
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void periodTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periodTextFieldActionPerformed

    private void calcAmortizationTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcAmortizationTableButtonActionPerformed

        //make sure all the required fields have values in them
        String amountStr = amountTextField.getText().replaceAll(",", ".");
        String periodStr = periodTextField.getText();
        String rateStr = rateTextField.getText().replaceAll(",", ".");

        if (amountStr.length() > 0 && periodStr.length() > 0 && rateStr.length() > 0) {
            //calculate the amortization
            Amortization am = this.calculateAmortization();
            //initialize the amortization table object
            AmortizationTable amTable=new AmortizationTable(this.createTableHeader(),am);
            AmortizationTableWindow a = new AmortizationTableWindow();
            a.setAmTableString(amTable.amortizationTableString());
            a.runAmTable();

        }


    }//GEN-LAST:event_calcAmortizationTableButtonActionPerformed

    private Amortization calculateAmortization() {
        String amountStr = amountTextField.getText().replaceAll(",", ".");
        String periodStr = periodTextField.getText();
        String rateStr = rateTextField.getText().replaceAll(",", ".");
        double amount = Double.parseDouble(amountStr);
        double period = Double.parseDouble(periodStr);
        double rate = Double.parseDouble(rateStr);

        Amortization am = null;
        int amortizationPayoffFrequencySelection = payoffFrequencyComboBox.getSelectedIndex();
        if (amortizationPayoffFrequencySelection == 0)//if the user has selected monthly frequency
        {
            am = new Amortization(amount, period, rate, 12);
        } else if (amortizationPayoffFrequencySelection == 1)//if the user has selected 3 month periods
        {
            am = new Amortization(amount, period, rate, 4);
        } else if (amortizationPayoffFrequencySelection == 2)//if the user has selected 6 month periods
        {
            am = new Amortization(amount, period, rate, 2);
        } else if (amortizationPayoffFrequencySelection == 3)//if the user has selected 1 year periods
        {
            am = new Amortization(amount, period, rate, 1);
        }

        return am;
    }

    /**
     * This method will fill a string with the details from the amortization form
     * related with period, amount, interest rate
     *
     * @return
     */
    private String createTableHeader()
    {
        String th="";
        th+=java.util.ResourceBundle.getBundle("gr/oncrete/nick/myBill/UserInterface/myBillUIBundle").getString("AMOUNT: ")+amountTextField.getText();
        th+="\n"+java.util.ResourceBundle.getBundle("gr/oncrete/nick/myBill/UserInterface/myBillUIBundle").getString("DURATION: ")+periodTextField.getText();
        th+="\n"+java.util.ResourceBundle.getBundle("gr/oncrete/nick/myBill/UserInterface/myBillUIBundle").getString("INTEREST RATE: ")+rateTextField.getText();
        th+="\n"+java.util.ResourceBundle.getBundle("gr/oncrete/nick/myBill/UserInterface/myBillUIBundle").getString("FREQUENCY: ")+payoffFrequencyComboBox.getSelectedItem().toString();

        return th;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CalculateAmortizationFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTextField;
    private javax.swing.JButton calcAmortizationTableButton;
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox payoffFrequencyComboBox;
    private javax.swing.JLabel periodLabel;
    private javax.swing.JTextField periodTextField;
    private javax.swing.JLabel presentResultLabel;
    private javax.swing.JLabel rateLabel;
    private javax.swing.JTextField rateTextField;
    private javax.swing.JLabel resultLabel;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    public void calcAmortization() {
        this.setVisible(true);
    }
}
