/*
 *  Copyright (C) 2010 nickapos
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * AboutWindow.java
 * This class will create a window with a text area and depending on the need
 * will present in the text are a message, be it an about or a readme.
 * Created on 11 Αυγ 2010, 9:51:33 μμ
 */
package gr.oncrete.nick.mybill.UserInterface;

import gr.oncrete.nick.myBill.BusinessLogic.NewThreadMassiveChangeCurrency;
import javax.swing.SwingUtilities;
import javax.swing.JLabel;
/**
 *
 * @author nickapos
 */
public class ConvertToNewCurrencyFrame extends javax.swing.JFrame {

    /** Creates new form AboutWindow */
    public ConvertToNewCurrencyFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        presentExchangeRatesButton = new javax.swing.JButton();
        rateTextField = new javax.swing.JTextField();
        executeButton = new javax.swing.JButton();
        progressLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("gr/oncrete/nick/myBill/UserInterface/myBillUIBundle"); // NOI18N
        setTitle(bundle.getString("ConvertToNewCurrencyFrame.title")); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setText(bundle.getString("ConvertToNewCurrencyFrame.jLabel2.text")); // NOI18N
        getContentPane().add(jLabel2);

        jLabel1.setText(bundle.getString("ConvertToNewCurrencyFrame.jLabel1.text")); // NOI18N
        getContentPane().add(jLabel1);

        presentExchangeRatesButton.setText(bundle.getString("ConvertToNewCurrencyFrame.presentExchangeRatesButton.text")); // NOI18N
        presentExchangeRatesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentExchangeRatesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(presentExchangeRatesButton);

        rateTextField.setText(bundle.getString("ConvertToNewCurrencyFrame.rateTextField.text")); // NOI18N
        getContentPane().add(rateTextField);

        executeButton.setText(bundle.getString("ConvertToNewCurrencyFrame.executeButton.text")); // NOI18N
        executeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(executeButton);

        progressLabel.setText(bundle.getString("ConvertToNewCurrencyFrame.progressLabel.text")); // NOI18N
        getContentPane().add(progressLabel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeButtonActionPerformed

        String rateStr = rateTextField.getText().replaceAll(",", ".");
        if (rateStr.length() > 0) {
            NewThreadMassiveChangeCurrency mc = new NewThreadMassiveChangeCurrency(rateStr,progressLabel);
            mc.execute();
        }

    }//GEN-LAST:event_executeButtonActionPerformed

    private void presentExchangeRatesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentExchangeRatesButtonActionPerformed
        ExchangeRatesFrame exrf = new ExchangeRatesFrame();
        exrf.presentExchangeRateFrame();
    }//GEN-LAST:event_presentExchangeRatesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ConvertToNewCurrencyFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton executeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton presentExchangeRatesButton;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JTextField rateTextField;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    public void showFrame() {
        this.setVisible(true);
    }
}
