/*
 *  Copyright (C) 2010 nickapos
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * AboutWindow.java
 * This class will create a window with a text area and depending on the need
 * will present in the text are a message, be it an about or a readme.
 * Created on 11 Αυγ 2010, 9:51:33 μμ
 */
package gr.oncrete.nick.mybill.UserInterface;

import java.util.*;
import java.text.*;
import gr.oncrete.nick.mybill.BusinessLogic.SelectInfo.DumpDatabase;
import gr.oncrete.nick.myBill.BusinessLogic.FileHandlers.MyFileWriter;
import gr.oncrete.nick.myBill.BusinessLogic.FileHandlers.NewThreadFileWriter;

/**
 *
 * @author nickapos
 */
public class ExportCSVByPeriod extends javax.swing.JFrame {

    /** Creates new form AboutWindow */
    public ExportCSVByPeriod() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        startDateSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        endDateSpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        validateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/myBillUIBundle"); // NOI18N
        setTitle(bundle.getString("ExportCSVByPeriod.title")); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(bundle.getString("ExportCSVByPeriod.jLabel2.text")); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2);

        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        jLabel4.setText(bundle.getString("ExportCSVByPeriod.jLabel4.text")); // NOI18N
        jPanel1.add(jLabel4);

        startDateSpinner.setModel(new javax.swing.SpinnerDateModel());
        startDateSpinner.setToolTipText(bundle.getString("ExportCSVByPeriod.startDateSpinner.toolTipText")); // NOI18N
        jPanel1.add(startDateSpinner);

        jLabel1.setText(bundle.getString("ExportCSVByPeriod.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel1);

        endDateSpinner.setModel(new javax.swing.SpinnerDateModel());
        endDateSpinner.setToolTipText(bundle.getString("ExportCSVByPeriod.endDateSpinner.toolTipText")); // NOI18N
        jPanel1.add(endDateSpinner);

        jLabel5.setText(bundle.getString("ExportCSVByPeriod.jLabel5.text")); // NOI18N
        jPanel1.add(jLabel5);

        validateButton.setText(bundle.getString("ExportCSVByPeriod.validateButton.text")); // NOI18N
        validateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(validateButton);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateButtonActionPerformed
        Date std = (Date) startDateSpinner.getValue();
        Date edd = (Date) endDateSpinner.getValue();
        SimpleDateFormat df1 = new SimpleDateFormat("yyyy-MM-dd");
        //System.out.println(""+df1.format(std));
        //System.out.println(""+df1.format(edd));
        try {
            df1.parse("" + df1.format(std));
            df1.parse("" + df1.format(edd));
            DumpDatabase dump = new DumpDatabase();
            ArrayList a = dump.getRecordsForAPeriod("" + df1.format(std), "" + df1.format(edd));
            //this.writeFile("eforia-"+df1.format(d1)+".csv", a);
            this.writeFileNewThread("period_" + df1.format(std) + "_" + df1.format(edd) + ".csv", a);
        } catch (ParseException pe) {
            System.out.println("invalid date " + std);
            System.out.println("invalid date " + edd);
        }

    }//GEN-LAST:event_validateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ExportCSVByPeriod().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner endDateSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner startDateSpinner;
    private javax.swing.JButton validateButton;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    public void displayGUI() {
        this.setVisible(true);
    }

    /**
     * method used to export the database into csv's
     *
     * @param filename
     * @param a
     */
    private void writeFile(String filename, ArrayList a) {
        MyFileWriter m = new MyFileWriter();
        m.createFile(filename);
        Iterator i = a.iterator();
        while (i.hasNext()) {
            String nextLine = (String) i.next();
            if (nextLine.length() > 0) {
                System.out.println(nextLine);
                m.writeToFile(nextLine);
            }
        }
        m.closeFile();
    }

    /**
     * this method can be used to write a file
     * in a new separate thread
     * @param filename
     * @param a
     */
    private void writeFileNewThread(String filename, ArrayList a) {
        String content = "";
        Iterator i = a.iterator();
        while (i.hasNext()) {
            String nextLine = (String) i.next();
            if (nextLine.length() > 0) {
                content = content + nextLine + "\n";
                System.out.println(nextLine);
            }
        }
        NewThreadFileWriter m = new NewThreadFileWriter(filename, content);
        m.execute();

    }
}
