/*
 *  Copyright (C) 2010 nickapos
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

 /*
 * AboutWindow.java
 * This class will create a window with a text area and depending on the need
 * will present in the text are a message, be it an about or a readme.
 * Created on 11 Αυγ 2010, 9:51:33 μμ
 */
package gr.oncrete.nick.mybill.UserInterface;

import gr.oncrete.nick.mybill.BusinessLogic.ImportDB.ImportBillsTable;
import gr.oncrete.nick.mybill.BusinessLogic.ImportDB.ImportCategoriesTable;
import gr.oncrete.nick.mybill.BusinessLogic.ImportDB.ImportCompaniesTable;
import gr.oncrete.nick.mybill.BusinessLogic.ImportDB.ImportIncomeTable;
import gr.oncrete.nick.mybill.BusinessLogic.SelectInfo.SelectAllBillsIDS;
import gr.oncrete.nick.mybill.BusinessLogic.SelectInfo.SelectAllCompaniesIDS;

/**
 *
 * @author nickapos
 */
public class ImportAllRecords extends javax.swing.JFrame {

    //the main user interface we will need to refresh after the import
    billsUI mainUI;
    //the counter that will hold the number of affected rows
    int counter = 0;

    /**
     * Creates new form AboutWindow
     */
    public ImportAllRecords(billsUI a) {
        initComponents();
        mainUI = a;
    }

    /**
     * Creates new form AboutWindow
     */
    public ImportAllRecords() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        validateButton = new javax.swing.JButton();
        rowsAffectedLabel = new javax.swing.JLabel();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/myBillUIBundle"); // NOI18N
        jLabel1.setText(bundle.getString("ImportAllRecords.jLabel1.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(bundle.getString("ImportAllRecords.title")); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout(0, 1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(bundle.getString("ImportAllRecords.jLabel2.text")); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2);

        validateButton.setText(bundle.getString("ImportAllRecords.validateButton.text")); // NOI18N
        validateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(validateButton);

        rowsAffectedLabel.setText(bundle.getString("ImportAllRecords.rowsAffectedLabel.text")); // NOI18N
        getContentPane().add(rowsAffectedLabel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateButtonActionPerformed
        int rowsAffected = 0;
        SelectAllCompaniesIDS s = new SelectAllCompaniesIDS();
        SelectAllBillsIDS s1 = new SelectAllBillsIDS();
        if (s.isEmpty() && s1.isEmpty()) {
            ImportCategoriesTable impCat = new ImportCategoriesTable();
            impCat.importFileToDB();
            rowsAffected += impCat.getRowsAffected();

            ImportCompaniesTable impComp = new ImportCompaniesTable();
            impComp.importFileToDB();
            rowsAffected += impComp.getRowsAffected();

            ImportBillsTable impBill = new ImportBillsTable();
            impBill.importFileToDB();
            rowsAffected += impBill.getRowsAffected();

            ImportIncomeTable impIncome = new ImportIncomeTable();
            impIncome.importFileToDB();
            rowsAffected += impIncome.getRowsAffected();

            //update the rows affected of the ui
            this.updateRowsAffectedCount(rowsAffected);
            if (mainUI != null) {
                mainUI.refreshCompaniesCombo();
                mainUI.refreshCatIDCombo();
            }

        } else {
            PopupMessageFrame mes = new PopupMessageFrame();
            mes.setNotification(java.util.ResourceBundle.getBundle("i18n/myBillUIBundle").getString("THE-DATABASE-IS-NOT-EMPTY.Ι-WILL-DO-NOTHING"));
        }

    }//GEN-LAST:event_validateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ImportAllRecords().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel rowsAffectedLabel;
    private javax.swing.JButton validateButton;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    public void displayGUI() {
        this.setVisible(true);
    }

    /**
     * this method will update the rows affected label with the number of rows
     * exported
     *
     * @param rows
     */
    private void updateRowsAffectedCount(int rows) {
        String defaultLabel = java.util.ResourceBundle.getBundle("i18n/myBillUIBundle").getString(" ROWS IMPORTED: ");
        rowsAffectedLabel.setText(defaultLabel + rows);
    }
}
