/*
 *  Copyright (C) 2010 nickapos
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * AboutWindow.java
 * This class will create a window with a text area and depending on the need
 * will present in the text are a message, be it an about or a readme.
 * Created on 11 Αυγ 2010, 9:51:33 μμ
 */
package gr.oncrete.nick.mybill.UserInterface;

import gr.oncrete.nick.myBill.BusinessLogic.SelectInfo.Category;
import gr.oncrete.nick.myBill.BusinessLogic.SelectInfo.SelectAllCompaniesPerCategory;
import gr.oncrete.nick.myBill.BusinessLogic.Categories;
import gr.oncrete.nick.myBill.BusinessLogic.NewThreadMergeCategories;
import javax.swing.JComboBox;
import java.util.List;
/**
 *
 * @author nickapos
 */
public class MergeCategoriesFrame extends javax.swing.JFrame {

    JComboBox box;
    String[] comboBoxActions = {java.util.ResourceBundle.getBundle("gr/oncrete/nick/myBill/UserInterface/myBillUIBundle").getString("INSERT"), java.util.ResourceBundle.getBundle("gr/oncrete/nick/myBill/UserInterface/myBillUIBundle").getString("EDIT"), java.util.ResourceBundle.getBundle("gr/oncrete/nick/myBill/UserInterface/myBillUIBundle").getString("DELETE")};//the dropdown list at the action combo boxes

    /** Creates new form AboutWindow
     * @param a
     */
    public MergeCategoriesFrame(JComboBox a) {
        box = a;
        initComponents();
    }

    /**
     * 
     */
    public MergeCategoriesFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        westPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        catToBeMergedComboBox = new javax.swing.JComboBox();
        catToRemainComboBox = new javax.swing.JComboBox();
        bottomPanel = new javax.swing.JPanel();
        goButton = new javax.swing.JButton();
        progressLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("gr/oncrete/nick/myBill/UserInterface/myBillUIBundle"); // NOI18N
        setTitle(bundle.getString("MergeCategoriesFrame.title")); // NOI18N
        setName("Manage Categories"); // NOI18N

        westPanel.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setText(bundle.getString("MergeCategoriesFrame.jLabel1.text")); // NOI18N
        westPanel.add(jLabel1);

        jLabel2.setText(bundle.getString("MergeCategoriesFrame.jLabel2.text")); // NOI18N
        westPanel.add(jLabel2);

        getContentPane().add(westPanel, java.awt.BorderLayout.WEST);

        rightPanel.setLayout(new java.awt.GridLayout(0, 1));

        catToBeMergedComboBox.setModel(new javax.swing.DefaultComboBoxModel(this.getCategoriesCombo()));
        catToBeMergedComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catToBeMergedComboBoxActionPerformed(evt);
            }
        });
        rightPanel.add(catToBeMergedComboBox);

        catToRemainComboBox.setModel(new javax.swing.DefaultComboBoxModel(this.getCategoriesCombo()));
        rightPanel.add(catToRemainComboBox);

        getContentPane().add(rightPanel, java.awt.BorderLayout.EAST);

        bottomPanel.setLayout(new java.awt.GridLayout(1, 0));

        goButton.setText(bundle.getString("MergeCategoriesFrame.goButton.text")); // NOI18N
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });
        bottomPanel.add(goButton);

        progressLabel.setText(bundle.getString("MergeCategoriesFrame.progressLabel.text")); // NOI18N
        bottomPanel.add(progressLabel);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catToBeMergedComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catToBeMergedComboBoxActionPerformed
    }//GEN-LAST:event_catToBeMergedComboBoxActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        String catToBeMergedName = (String) catToBeMergedComboBox.getSelectedItem();
        Category categToBeMerged = new Category();
        categToBeMerged.selectCatByName(catToBeMergedName);
        SelectAllCompaniesPerCategory companyIdsToBeMerged=new SelectAllCompaniesPerCategory(categToBeMerged.getCatID());
        List idList=companyIdsToBeMerged.getIds();
      

        String catToRemainName = (String) catToRemainComboBox.getSelectedItem();
        Category catToRemain = new Category();
        catToRemain.selectCatByName(catToRemainName);

        NewThreadMergeCategories merge = new NewThreadMergeCategories(idList,catToRemain.getCatID(),progressLabel);
        merge.doInBackground();

    }//GEN-LAST:event_goButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MergeCategoriesFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JComboBox catToBeMergedComboBox;
    private javax.swing.JComboBox catToRemainComboBox;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel westPanel;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    public void displayApp() {
        this.setVisible(true);
    }

    private String[] getCategoriesCombo() {
        Categories com = new Categories();
        return com.categoriesNames();
    }

    private void refreshCatIDCombo() {
        catToRemainComboBox.setModel(new javax.swing.DefaultComboBoxModel(this.getCategoriesCombo()));
    }

    /**
     * refresh the combo at the mail interface
     */
    private void refreshMainCatIDCombo() {
        box.setModel(new javax.swing.DefaultComboBoxModel(this.getCategoriesCombo()));
    }
}
