/*
 *  Copyright (C) 2010 nickapos
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * AboutWindow.java
 * This class will create a window with a text area and depending on the need
 * will present in the text are a message, be it an about or a readme.
 * Created on 11 Αυγ 2010, 9:51:33 μμ
 */
package gr.oncrete.nick.mybill.UserInterface;

import gr.oncrete.nick.mybill.BusinessLogic.Companies;
import gr.oncrete.nick.mybill.BusinessLogic.SelectInfo.SelectCompanyDetails;
import gr.oncrete.nick.mybill.BusinessLogic.SelectInfo.SelectAllBillsDetailsForSpecificCompany;
import gr.oncrete.nick.mybill.BusinessLogic.SelectInfo.SelectAllIncomeDetailsForSpecificCompany;
import java.util.*;
import javax.swing.JComboBox;

/**
 *
 * @author nickapos
 */
public class PresentTransactionsPerCompany extends javax.swing.JFrame {

    JComboBox box;
    String[] comboBoxActions = {java.util.ResourceBundle.getBundle("i18n/myBillUIBundle").getString("INSERT"), java.util.ResourceBundle.getBundle("i18n/myBillUIBundle").getString("EDIT"), java.util.ResourceBundle.getBundle("i18n/myBillUIBundle").getString("DELETE")};//the dropdown list at the action combo boxes

    /** Creates new form AboutWindow
     * @param a
     */
    public PresentTransactionsPerCompany(JComboBox a) {
        box = a;
        initComponents();
    }

    /**
     * 
     */
    public PresentTransactionsPerCompany() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        transactionTypeComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        companyComboBox = new javax.swing.JComboBox();
        centerPanel = new javax.swing.JPanel();
        goButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/myBillUIBundle"); // NOI18N
        setTitle(bundle.getString("PresentTransactionsPerCompany.title")); // NOI18N
        setName("Manage Categories"); // NOI18N

        northPanel.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setText(bundle.getString("PresentTransactionsPerCompany.jLabel1.text")); // NOI18N
        northPanel.add(jLabel1);

        transactionTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Expenses", "Income" }));
        transactionTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionTypeComboBoxActionPerformed(evt);
            }
        });
        northPanel.add(transactionTypeComboBox);

        jLabel2.setText(bundle.getString("PresentTransactionsPerCompany.jLabel2.text")); // NOI18N
        northPanel.add(jLabel2);

        companyComboBox.setModel(new javax.swing.DefaultComboBoxModel(this.getCompaniesCombo()));
        northPanel.add(companyComboBox);

        getContentPane().add(northPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setLayout(new java.awt.BorderLayout());

        goButton.setText(bundle.getString("PresentTransactionsPerCompany.goButton.text")); // NOI18N
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });
        centerPanel.add(goButton, java.awt.BorderLayout.NORTH);

        resultTextArea.setColumns(20);
        resultTextArea.setRows(5);
        jScrollPane1.setViewportView(resultTextArea);

        centerPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transactionTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionTypeComboBoxActionPerformed
    }//GEN-LAST:event_transactionTypeComboBoxActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        int a = transactionTypeComboBox.getSelectedIndex();
        String companyName = (String) companyComboBox.getSelectedItem();
        SelectCompanyDetails cd = new SelectCompanyDetails();
        cd.SelectCompanyDetailsWithName(companyName);
        String resultStr = "";
        if (a == 0) //the action is expenses
        {
            SelectAllBillsDetailsForSpecificCompany salb = new SelectAllBillsDetailsForSpecificCompany(cd.getID());
            List billResults = salb.getAllRows();

            if (billResults != null) {
                Iterator it = billResults.iterator();
                while (it.hasNext()) {
                    String next = (String) it.next();
                    resultStr = resultStr + "\n" + next;
                }
                resultStr = this.getNumOfRowsLine(billResults, resultStr);
            }
        } else if (a == 1) //the action is income
        {
            SelectAllIncomeDetailsForSpecificCompany sali = new SelectAllIncomeDetailsForSpecificCompany(cd.getID());
            List incomeResults = sali.getAllRows();

            if (incomeResults != null) {
                Iterator it = incomeResults.iterator();
                while (it.hasNext()) {
                    String next = (String) it.next();
                    resultStr = resultStr + "\n" + next;
                }
            }
            resultStr = this.getNumOfRowsLine(incomeResults, resultStr);
        }
        resultTextArea.setText(resultStr);
    }//GEN-LAST:event_goButtonActionPerformed
    private String getNumOfRowsLine(List a, String results) {
        return results + "\n\n" + java.util.ResourceBundle.getBundle("i18n/myBillUIBundle").getString("NUMBER OF ROWS ")+" " + a.size();


    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PresentTransactionsPerCompany().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JComboBox companyComboBox;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel northPanel;
    private javax.swing.JTextArea resultTextArea;
    private javax.swing.JComboBox transactionTypeComboBox;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    public void displayApp() {
        this.setVisible(true);
    }

    private String[] getCompaniesCombo() {
        Companies com = new Companies();
        return com.companyNames();
    }
}
